[env:esp32dev]
extra_scripts = pre:tools/pre_build.py
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/RTClib@^2.1.1
    sparkfun/SparkFun Qwiic Humidity AHT20
    sparkfun/SparkFun Indoor Air Quality Sensor - ENS160
    bblanchon/ArduinoJson@^7.0.0
    knolleary/PubSubClient@^2.8
